name: Build and deploy ASP.Net Core app to Azure Web App - WorkoutProgramBuilder

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build app
        run: dotnet build --configuration Release --no-restore

      - name: Publish app
        run: dotnet publish -c Release -r win-x86 --self-contained true -o ./publish

      - name: Create ZIP package
        run: Compress-Archive -Path ./publish/* -DestinationPath ./publish.zip

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: app-package
          path: ./publish.zip

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-package

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DD711B61929C4E3D97020A16F5F3E7EF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DA38AE8B0B1D4191964A7A544B10362F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7759EAA3B9A44C05B1C509FE4A2673CD }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'WorkoutProgramBuilder'
          slot-name: 'Production'
          package: './publish.zip'
          deployment-method: runFromPackage
